#!/usr/bin/env python3
import skilstak.colors as c

answers = [
    "Nope",
    "No",
    "Yes",
    "Definitly",
    "Maybe"
]

eastereggs = [
    ["Die|Die", "You Died"]
    
]        



print(c.clear)
print(c.yellow + " Welcome to the Magic Eightball.")








